# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Comment

# Model Form Field configuration
form: $/wboyz/commentsystem/models/comment/fields.yaml

# Model Class name
modelClass: Wboyz\CommentSystem\Models\Comment

# Default redirect location
defaultRedirect: wboyz/commentsystem/comments

# Create page
create:
    title: Create Comment
    redirect: wboyz/commentsystem/comments/update/:id
    redirectClose: wboyz/commentsystem/comments

# Update page
update:
    title: Edit Comment
    redirect: wboyz/commentsystem/comments
    redirectClose: wboyz/commentsystem/comments

# Preview page
preview:
    title: Preview Comment